baseURL = "https://www.walkerlab.org/"
languageCode = "en-us"
title = "Walker Group"
theme = "terminal"
paginate = 6

[markup.goldmark.renderer]
  unsafe=true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  dir = "content/posts/"
  contentTypeName = "News"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Walker Lab"
    subtitle = "Excited states and fluorescence in biomolecules"
    owner = "A. R. Walker"
    keywords = "computational chemistry"
    copyright = "ARW"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Walker Lab"
      logoHomeLink = "/posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "research"
        name = "0:Research"
        url = "/Research"
      [[languages.en.menu.main]]
        identifier = "people"
        name = "1:People"
        url = "/People"
      [[languages.en.menu.main]]
        identifier = "publications"
        name = "2:Publications"
        url = "/Publications"
      [[languages.en.menu.main]]
        identifier = "class"
        name = "4:Teaching"
        url = "/Classes"
      [[languages.en.menu.main]]
        identifier = "jobs"
        name = "3:Job Openings"
        url = "/JobOpenings"
      [[languages.en.menu.main]]
        identifier = "wiki"
        name = "5:Wiki"
        url = "/Wiki"
